### ISSUE TITLE
Theoretical part - the Semantics

### ISSUE THREAD

**Issue by mathooo** [sybila/BCSgen#1]
1. Find the border between human-readable and executable part of BCSL
     * set the exact mapping between these two parts
     * **Note**: one executable rule represents one action, i.e. the mapping is not necessarily 1:1
2. For the executable part determine properties for reaction types:
     * state change
     * complex formation/dissociation
     * degradation/translation
           * presence of an entity (modifier) ?
3. define *matching*
     * \lhd operators defined in syntax can be used
     * the syntax can be extended by nesting complexes
          * define \lhd for complexes
4. define *replacement*
     * after matching determine what reaction type does the rule stands for
     * transformation can be applied (only ONE step !)

**Comment by xsafran1** [comment]
That sounds challenging� ;)

D.
